"""Added model for app admins

Revision ID: 2110c1a297
Revises: 4d2a46b2275
Create Date: 2015-05-03 22:43:43.913006

"""

# revision identifiers, used by Alembic.
revision = '2110c1a297'
down_revision = '4d2a46b2275'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import GDGUkraine.model
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdg_admins',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('filter_place', mysql.INTEGER(), nullable=True),
    sa.Column('googler_id', mysql.INTEGER(), nullable=True),
    sa.Column('godmode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['filter_place'], ['gdg_places.id'], ),
    sa.ForeignKeyConstraint(['googler_id'], ['gdg_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gdg_admins_email'), 'gdg_admins', ['email'], unique=True)
    op.create_index(op.f('ix_gdg_admins_filter_place'), 'gdg_admins', ['filter_place'], unique=False)
    op.create_index(op.f('ix_gdg_admins_googler_id'), 'gdg_admins', ['googler_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_gdg_admins_googler_id'), table_name='gdg_admins')
    # op.drop_index(op.f('ix_gdg_admins_filter_place'), table_name='gdg_admins')
    op.drop_index(op.f('ix_gdg_admins_email'), table_name='gdg_admins')
    op.drop_table('gdg_admins')
    ### end Alembic commands ###
