"""Add missing master reference to the Place model

Revision ID: 23806f003e6
Revises: 39eb5eb1317
Create Date: 2016-01-10 18:47:32.447399

"""

# revision identifiers, used by Alembic.
revision = '23806f003e6'
down_revision = '39eb5eb1317'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import GDGUkraine.model
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gdg_places', sa.Column('master_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'gdg_places', 'gdg_places', ['master_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gdg_places', type_='foreignkey')
    op.drop_column('gdg_places', 'master_id')
    ### end Alembic commands ###
