"""Added missing 'confirmed' column to EventParticipant model

Revision ID: 2b2d619f50e
Revises: 30911189537
Create Date: 2016-01-03 22:36:29.490717

"""

# revision identifiers, used by Alembic.
revision = '2b2d619f50e'
down_revision = '30911189537'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import GDGUkraine.model


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gdg_events_participation', sa.Column('confirmed', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gdg_events_participation', 'confirmed')
    ### end Alembic commands ###
