"""Add missing 'testing' and 'require_confirmation' columns to the Event model

Revision ID: 39eb5eb1317
Revises: 2b2d619f50e
Create Date: 2016-01-10 18:41:33.921313

"""

# revision identifiers, used by Alembic.
revision = '39eb5eb1317'
down_revision = '2b2d619f50e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import GDGUkraine.model


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gdg_events', sa.Column('require_confirmation', sa.Boolean(), nullable=False))
    op.add_column('gdg_events', sa.Column('testing', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gdg_events', 'testing')
    op.drop_column('gdg_events', 'require_confirmation')
    ### end Alembic commands ###
