"""Initial migration

Revision ID: 47d48ad28c
Revises: 
Create Date: 2015-05-02 12:36:30.227120

"""

# revision identifiers, used by Alembic.
revision = '47d48ad28c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import GDGUkraine.model


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdg_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('geo', sa.String(length=30), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('show', sa.Enum('1', '0', name='show'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gdg_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('surname', sa.String(length=35), nullable=False),
    sa.Column('nickname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gplus', sa.String(length=128), nullable=True),
    sa.Column('hometown', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('www', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.Enum('newbie', 'elementary', 'intermediate', 'advanced', 'jedi', name='experience_level'), nullable=True),
    sa.Column('experience_desc', sa.UnicodeText(), nullable=True),
    sa.Column('interests', sa.UnicodeText(), nullable=True),
    sa.Column('events_visited', sa.UnicodeText(), nullable=True),
    sa.Column('english_knowledge', sa.Enum('elementary', 'intermediate', 'upper intermediate', 'advanced', 'native', name='english_knowledge'), nullable=True),
    sa.Column('t_shirt_size', sa.Enum('S', 'M', 'L', 'XL', 'XXL', name='t_shirt_size'), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('additional_info', sa.UnicodeText(), nullable=True),
    sa.Column('local_gdg_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('www')
    )
    op.create_index(op.f('ix_gdg_participants_company'), 'gdg_participants', ['company'], unique=False)
    op.create_index(op.f('ix_gdg_participants_email'), 'gdg_participants', ['email'], unique=True)
    op.create_index(op.f('ix_gdg_participants_gplus'), 'gdg_participants', ['gplus'], unique=True)
    op.create_index(op.f('ix_gdg_participants_hometown'), 'gdg_participants', ['hometown'], unique=False)
    op.create_index(op.f('ix_gdg_participants_local_gdg_id'), 'gdg_participants', ['local_gdg_id'], unique=False)
    op.create_index(op.f('ix_gdg_participants_nickname'), 'gdg_participants', ['nickname'], unique=True)
    op.create_index(op.f('ix_gdg_participants_phone'), 'gdg_participants', ['phone'], unique=True)
    op.create_index(op.f('ix_gdg_participants_position'), 'gdg_participants', ['position'], unique=False)
    op.create_table('gdg_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.UnicodeText(), nullable=False),
    sa.Column('gplus_event_id', sa.String(length=27), nullable=True),
    sa.Column('host_gdg_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('closereg', sa.Date(), nullable=True),
    sa.Column('fields', GDGUkraine.model.JSONEncodedDict(length=512), nullable=True),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('max_regs', sa.Integer(), nullable=True),
    sa.Column('google_map_iframe', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['host_gdg_id'], ['gdg_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gdg_events_gplus_event_id'), 'gdg_events', ['gplus_event_id'], unique=True)
    op.create_index(op.f('ix_gdg_events_host_gdg_id'), 'gdg_events', ['host_gdg_id'], unique=False)
    op.create_table('gdg_events_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('googler_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.Column('fields', GDGUkraine.model.JSONEncodedDict(length=512), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['gdg_events.id'], ),
    sa.ForeignKeyConstraint(['googler_id'], ['gdg_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('googler_id', 'event_id', name='unique_participation')
    )
    op.create_index(op.f('ix_gdg_events_participation_event_id'), 'gdg_events_participation', ['event_id'], unique=False)
    op.create_index(op.f('ix_gdg_events_participation_googler_id'), 'gdg_events_participation', ['googler_id'], unique=False)
    op.create_table('gdg_invites',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['gdg_events.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gdg_invites')
    op.drop_index(op.f('ix_gdg_events_participation_googler_id'), table_name='gdg_events_participation')
    op.drop_index(op.f('ix_gdg_events_participation_event_id'), table_name='gdg_events_participation')
    op.drop_table('gdg_events_participation')
    op.drop_index(op.f('ix_gdg_events_host_gdg_id'), table_name='gdg_events')
    op.drop_index(op.f('ix_gdg_events_gplus_event_id'), table_name='gdg_events')
    op.drop_table('gdg_events')
    op.drop_index(op.f('ix_gdg_participants_position'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_phone'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_nickname'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_local_gdg_id'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_hometown'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_gplus'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_email'), table_name='gdg_participants')
    op.drop_index(op.f('ix_gdg_participants_company'), table_name='gdg_participants')
    op.drop_table('gdg_participants')
    op.drop_table('gdg_places')
    ### end Alembic commands ###
