"""Added XS value to ENUM of participant's t-shirt size

Revision ID: 4d2a46b2275
Revises: 47d48ad28c
Create Date: 2015-05-02 13:01:34.514873

"""

# revision identifiers, used by Alembic.
revision = '4d2a46b2275'
down_revision = '47d48ad28c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import GDGUkraine.model


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gdg_participants', 't_shirt_size',
                    existing_nullable=True, existing_server_default=False,
                    existing_type=sa.Enum('S', 'M', 'L', 'XL', 'XXL',
                                          name='t_shirt_size'),
                    type_=sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL',
                                  name='t_shirt_size'),
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gdg_participants', 't_shirt_size',
                    existing_nullable=True, existing_server_default=False,
                    existing_type=sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL',
                                          name='t_shirt_size'),
                    type_=sa.Enum('S', 'M', 'L', 'XL', 'XXL',
                                  name='t_shirt_size'),
                    )
    ### end Alembic commands ###
